# Generated by Django 4.2.7 on 2023-12-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='book',
            new_name='bookCopy',
        ),
    ]
