# Generated by Django 4.2.7 on 2023-12-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genres', models.CharField(choices=[('ACTI', 'Action'), ('SCIF', 'Science Fiction'), ('FANT', 'Fantasy'), ('NONF', 'Non Fiction'), ('MYST', 'Mystery')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('copyId', models.IntegerField(primary_key=True, serialize=False)),
                ('onLoan', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='Books.book')),
            ],
        ),
    ]
